server_format:
  BizyAir_KSampler: KSampler

service_config:
  service_address: http://0.0.0.0:9911 # https://api.siliconflow.cn # http://0.0.0.0:9911
  route: /supernode/test-bizyair-sdxl-comfy-ksampler
  service_route: "{{ service_config.service_address }}{{ service_config.route }}"

service_route: http://your-service-route-address

class_types:
  CLIPTextEncode:
    max_instances: 2
    node_ids: [3, 4]
  VAEDecode:
    max_instances: 1
    node_ids: [5]
  VAEEncode:
    max_instances: 1
    node_ids: [6]
  VAEEncodeForInpaint:
    max_instances: 1
    node_ids: [7]
  KSampler:
    max_instances: 1
    node_ids: [10]
    steps: [1, 30]
  IPAdapterUnifiedLoader:
    max_instances: 1
    node_ids: [11]
    inputs:
      preset:
        - "PLUS (high strength)"
  IPAdapter:
    max_instances: 1
    node_ids: [12]
  IPAdapterAdvanced:
    max_instances: 1
    node_ids: [13]
  CLIPVisionLoader:
    max_instances: 1
    node_ids: [14]
    inputs:
      clip_name:
        - "kolors/pytorch_model.bin"
  IPAdapterModelLoader:
    max_instances: 1
    node_ids: [15]
    inputs:
      ipadapter_file:
        - "kolors/ip_adapter_plus_general.bin"
  VAELoader:
    max_instances: 1
    node_ids: [16]
    inputs:
      vae_name:
        - "sdxl/sdxl_vae.safetensors"
  ComfyAirLoadData:
    max_instances: 10
    inputs:
      max_height: 1536
      max_width: 1536
